Write block entity nbt on networking thread instead of server one
ModFest/fireblanket pull request #4
Opened 2023-08-12 20:12 UTC by Patbox

This pr adds ServerPacketWriter, a utility interface for creation on CustomPayloadS2CPackets that write on networking thread. The implementation is lifted directly with polymer with few simplifications, since you don't need player context or packet version handling.

From my testing (within polymer) it indeed is faster (with most noticeable effect with large, nbt driven packets).

Ran this in singleplayer and all methods wrote and read data correctly

2023-08-14 17:14 UTC, jaskarth requested changes
Thanks! I have a few comments.

2023-08-14 17:14 UTC, jaskarth commented on src/main/java/net/modfest/fireblanket/mixin/MixinCustomPayloadS2CPacket.java
> +    * Battle tested in polymer™
```suggestion
```
Explain the "hack" here more

2023-08-14 17:14 UTC, jaskarth commented on src/main/java/net/modfest/fireblanket/mixin/MixinCustomPayloadS2CPacket.java
> +            var buf = cir.getReturnValue();
Avoid var (goes for everywhere)

2023-08-14 17:14 UTC, jaskarth commented on src/main/java/net/modfest/fireblanket/net/writer/ServerPacketWriter.java
> + * so I thought it would be good idea to bring it here.
Avoid first person in comments

2023-08-14 17:14 UTC, jaskarth commented on src/main/java/net/modfest/fireblanket/net/BundledBlockEntityUpdatePacket.java
> +public record BundledBlockEntityUpdatePacket(BEUpdate[] updates) implements ServerPacketWriter {
Does this need to be an array? If you keep the list you can remove the `toArray()` above, reducing an allocation

2023-08-14 17:16 UTC, Patbox commented on src/main/java/net/modfest/fireblanket/net/BundledBlockEntityUpdatePacket.java
> +public record BundledBlockEntityUpdatePacket(BEUpdate[] updates) implements ServerPacketWriter {
List was later cleared. Through using old list here and creating new one is also an option.

2023-08-14 17:16 UTC, Patbox commented on src/main/java/net/modfest/fireblanket/net/writer/ServerPacketWriter.java
> + * so I thought it would be good idea to bring it here.
I guess my comment style doesn't fit here. Will change that :p

2023-08-14 17:18 UTC, jaskarth commented on src/main/java/net/modfest/fireblanket/net/BundledBlockEntityUpdatePacket.java
> +public record BundledBlockEntityUpdatePacket(BEUpdate[] updates) implements ServerPacketWriter {
Ah, right. The array solution is probably fine here then.

2023-08-15 09:29 UTC, Patbox commented
Applied all suggestions

2023-08-19 01:33 UTC, jaskarth approved these changes
Looks good, thanks for this!

2023-08-19 01:41 UTC, merged